dist: trusty
sudo: required
language: node_js
node_js:
- '10'
cache:
  directories:
    - ~/.npm
    - node_modules
    - ~/.cache
  override:
    - npm ci
    - npm run cy:verify

addons:
  apt:
    packages:
      - docker-ce

jobs:
  include:
    - stage: test
      env:
        - DOCKER_COMPOSE_VERSION=1.22.0
      before_install:
        - sudo rm /usr/local/bin/docker-compose
        - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
        - chmod +x docker-compose
        - sudo mv docker-compose /usr/local/bin
      install:
        - docker build . -t rv-frontend
        - docker-compose -f docker-compose.test.yml up -d
        - sleep 15
        - docker-compose -f docker-compose.test.yml run backend yarn db-migrate
        - docker-compose -f docker-compose.test.yml run backend yarn db-seed
        - npm install
      after_script:
        - docker-compose -f docker-compose.test.yml down
      after_success:
        - "./docker-deploy.sh"
      script:
        - npm run lint-js
        - npm run lint-scss
        - npm test
        - npm run test:cypress

stages:
  - test