language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
install:
- npm i
- npm i -g codecov
script:
- npm test --coverage
- codecov
deploy:
  provider: heroku
  api_key:
    secure: XbFDPfqd0SkhXwDaAftwnYNiwRcEqljTJkS+OleOWamOyqnYp2d1Q2XXofLppcauUleLj0vp6vLhZBlHJ2zd7b8X4+SM9XHnW9eD1uIGLG8cbdUoedS05fGB2MDL0v03ZWO8tehjJBz0voTCtRSaVSdNO2BBm1o546f3eZCN8kISggYVZNl7uyiL/BoSZ/kBuBAPWq8xDE130BipUNx7ukBT3L81R428v7kID0WNKMxPntvp2N7yM2cHrQAGM+saPseAAlV1v4O3Kopf9AY5UiuRKGoz/EzDRaf6+GBEaDxFv71qFRVpVoU5FtfGhmACHPO88Klj2OObauYPV03bktEAzcvCFlJZOC7rp+SJoYaSDWpPov24zXPRewbx3HHE7Q2NtKA75vBeefWcDaC6NueSZSOXpdNRWKiwYmBfcusZVOhBHeLur+4W61TPehO4YHuunkpepHOI/4yPiV3T6pS7MfF4XML8n1kkI02+qkJSdK9rcAE454ogTuGEV5yT+uPbgwEDOREA+yYdVwHeQ7/ZLH1GmfSXhrgWpCec0IX/1I8SLWQ0YR1jLoeEDKwybl5w3wV0PwOleQBMSVpaDepk3jC5zguexWtAWKvk6wmrv7XVoK3PQIuiwTc/nv5WFQwjL/7pNXtkfLUZqNhtDQuhMmq74D+G5mL+TaLy6AY=
  app:
    develop: rv-frontend-dev
    master: rv-frontend
