version: '3'
services:
  backend:
    image: tkoaly/rv-backend:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=db
      - DB_USERNAME=rvadmin
      - DB_PASSWORD=unsecure
      - DB_NAME=rv
      - DB_PORT=5430
      - JWT_SECRET=unsecure
      - JWT_ADMIN_SECRET=unsecure
  db:
    image: postgres:10-alpine
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=rvadmin
      - POSTGRES_PASSWORD=unsecure
      - POSTGRES_DB=rv_dev