name: Push & Pull Request Continuous Integration

on: [push, pull_request]

jobs:
  install_deps:
    runs-on: ubuntu-18.04
    name: Install project dependencies
    strategy:
      matrix:
        node-version: [10.16.2]
    steps:
    - uses: actions/checkout@v1
      name: Git checkout
    - uses: actions/setup-node@v1
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
  lint_js:
    runs-on: ubuntu-18.04
    name: Lint JavaScript files
    steps:
    - uses: actions/checkout@v1
      name: Git checkout
    - uses: actions/setup-node@v1
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Lint JS
      run: npm run lint-js
      env:
        CI: true
        SASS_PATH: src
  lint_scss:
    runs-on: ubuntu-18.04
    name: Lint stylesheets
    steps:
    - uses: actions/checkout@v1
      name: Git checkout
    - uses: actions/setup-node@v1
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Lint SCSS
      run: npm run lint-scss
      env:
        CI: true
        SASS_PATH: src
  run_tests:
    runs-on: ubuntu-18.04
    name: Run Jest tests
    steps:
    - uses: actions/checkout@v1
      name: Git checkout
    - uses: actions/setup-node@v1
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Run tests
      run: npm test
      env:
        CI: true
  run_cypress_tests:
    runs-on: ubuntu-18.04
    name: Run Cypress tests
    steps:
    - uses: actions/checkout@v1
      name: Git checkout
    - name: Start RV back-end
      run: |
        docker-compose -f docker-compose.test.yml up -d --build
        docker-compose -f docker-compose.test.yml run backend yarn db-migrate
        docker-compose -f docker-compose.test.yml run backend yarn db-seed
    - uses: actions/setup-node@v1
      name: Use Node.js ${{ matrix.node-version }}
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm install
    - name: Execute Cypress
      run: npm run test:cypress     
      env:
        CI: true
        SASS_PATH: src
        REACT_APP_BACKEND_URL: http://localhost:8080
  push_docker_image:
    runs-on: ubuntu-18.04
    needs: [install_deps, lint_js, lint_scss, run_tests, run_cypress_tests]
    steps:
      - name: Push to Docker registry
        run: ./docker-deploy.sh
        on:
          push:
          pull_request:
            types: [closed]